---
## 1. What is NumPy?

NumPy provides:
- Efficient storage and operations on numeric data
- N-dimensional array object (`ndarray`)
- Mathematical functions for fast operations
- Tools for linear algebra, random numbers, and more

📚 **Documentation**: https://numpy.org/doc/

In [1]:
# Import NumPy with standard alias
import numpy as np

print(f"NumPy version: {np.__version__}")

NumPy version: 2.2.6


---
## 2. Python `array` Module vs NumPy

Python has a built-in `array` module, but NumPy is preferred for numerical computing.

In [2]:
# Python's built-in array module
import array

# 'i' = integer, 'f' = float
py_int_array = array.array('i', [1, 2, 3, 4])
py_float_array = array.array('f', [1.1, 2.2, 3.3])

print(f"Python int array: {py_int_array}")
print(f"Python float array: {py_float_array}")
print(f"Type: {type(py_int_array)}")

Python int array: array('i', [1, 2, 3, 4])
Python float array: array('f', [1.100000023841858, 2.200000047683716, 3.299999952316284])
Type: <class 'array.array'>


### Key Differences: `array.array` vs `np.ndarray`

| Feature | Python `array` | NumPy `ndarray` |
|---------|----------------|------------------|
| **Dimensions** | 1D only | N-dimensional |
| **Performance** | Python loops (slower) | C/Fortran optimized (fast) |
| **Data Types** | Limited ('i', 'f', etc.) | Many (int8, float64, complex128) |
| **Operations** | Basic only | Rich mathematical functions |
| **Use Case** | Simple homogeneous arrays | Scientific computing |

---
## 3. Creating NumPy Arrays from Lists

In [3]:
# From a Python list
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)

print(f"List: {my_list}")
print(f"NumPy Array: {arr}")
print(f"Type: {type(arr)}")

List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [4]:
# Float array
float_arr = np.array([1.1, 2.2, 3.3])
print(f"Float array: {float_arr}")
print(f"Data type: {float_arr.dtype}")

Float array: [1.1 2.2 3.3]
Data type: float64


In [5]:
# Type Upcasting: Mixed types → NumPy converts to common type
mixed_list = [1, 2, 3.5, 4]
mixed_arr = np.array(mixed_list)

print(f"Mixed list: {mixed_list}")
print(f"Array (upcasted): {mixed_arr}")  # All become floats!
print(f"Data type: {mixed_arr.dtype}")

Mixed list: [1, 2, 3.5, 4]
Array (upcasted): [1.  2.  3.5 4. ]
Data type: float64


In [6]:
# Explicit dtype specification
int_arr = np.array([1, 2, 3, 4], dtype='int32')
float_arr = np.array([1, 2, 3, 4], dtype='float64')

print(f"Int32 array: {int_arr}, dtype: {int_arr.dtype}")
print(f"Float64 array: {float_arr}, dtype: {float_arr.dtype}")

Int32 array: [1 2 3 4], dtype: int32
Float64 array: [1. 2. 3. 4.], dtype: float64


In [7]:
# Convert array back to list
arr = np.array([1, 2, 3, 4, 5])
back_to_list = arr.tolist()

print(f"Array: {arr}")
print(f"Back to list: {back_to_list}")
print(f"Type: {type(back_to_list)}")

Array: [1 2 3 4 5]
Back to list: [1, 2, 3, 4, 5]
Type: <class 'list'>


---
## 4. Array Attributes

Important attributes to know about an array:

In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(f"Array: {arr}")
print(f"dtype (data type): {arr.dtype}")
print(f"ndim (dimensions): {arr.ndim}")
print(f"shape (rows, cols): {arr.shape}")
print(f"size (total elements): {arr.size}")

Array: [1 2 3 4 5]
dtype (data type): int64
ndim (dimensions): 1
shape (rows, cols): (5,)
size (total elements): 5


In [9]:
# 2D array attributes
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"2D Array:\n{arr_2d}")
print(f"\nndim: {arr_2d.ndim}")
print(f"shape: {arr_2d.shape}  # (rows, columns)")
print(f"size: {arr_2d.size}  # 3 × 3 = 9")

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

ndim: 2
shape: (3, 3)  # (rows, columns)
size: 9  # 3 × 3 = 9


---
## 5. Creating Arrays with Default Values

In [10]:
# Array of zeros
zeros = np.zeros(5)
print(f"Zeros: {zeros}")

# Array of zeros (integer)
zeros_int = np.zeros(5, dtype=int)
print(f"Zeros (int): {zeros_int}")

Zeros: [0. 0. 0. 0. 0.]
Zeros (int): [0 0 0 0 0]


In [11]:
# Array of ones
ones = np.ones(5)
print(f"Ones: {ones}")

# 2D array of ones
ones_2d = np.ones((3, 4))  # 3 rows, 4 columns
print(f"\n2D Ones:\n{ones_2d}")

Ones: [1. 1. 1. 1. 1.]

2D Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# Empty array (uninitialized - contains garbage values)
empty = np.empty(5)
print(f"Empty (garbage values): {empty}")

Empty (garbage values): [1. 1. 1. 1. 1.]


In [13]:
# Identity matrix
identity = np.eye(4)  # 4×4 identity matrix
print(f"Identity Matrix:\n{identity}")

Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---
## 6. Creating Linear Sequence Arrays

In [14]:
# np.arange(start, stop, step) - like Python's range()
print(f"arange(0, 10): {np.arange(0, 10)}")
print(f"arange(0, 10, 2): {np.arange(0, 10, 2)}")
print(f"arange(5, 15, 3): {np.arange(5, 15, 3)}")

arange(0, 10): [0 1 2 3 4 5 6 7 8 9]
arange(0, 10, 2): [0 2 4 6 8]
arange(5, 15, 3): [ 5  8 11 14]


In [15]:
# np.linspace(start, stop, num) - evenly spaced values
# Formula: step = (stop - start) / (num - 1)

print(f"linspace(0, 1, 5): {np.linspace(0, 1, 5)}")
print(f"linspace(10, 20, 5): {np.linspace(10, 20, 5)}")

# Explanation: (20-10)/(5-1) = 2.5 step

linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
linspace(10, 20, 5): [10.  12.5 15.  17.5 20. ]


---
## 7. Multi-dimensional Arrays

In [16]:
# Create 2D array from nested lists
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = [7, 8, 9]

arr_2d = np.array([list1, list2, list3])
print(f"2D Array:\n{arr_2d}")
print(f"\nShape: {arr_2d.shape}")
print(f"Dimensions: {arr_2d.ndim}")

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape: (3, 3)
Dimensions: 2


In [17]:
# 2D arrays with default values
zeros_2d = np.zeros((3, 5))  # 3 rows, 5 columns
ones_2d = np.ones((4, 4))    # 4 rows, 4 columns

print(f"Zeros (3×5):\n{zeros_2d}")
print(f"\nOnes (4×4):\n{ones_2d}")

Zeros (3×5):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Ones (4×4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


---
## 8. Array Indexing

In [18]:
# 1D Indexing (same as lists)
arr = np.array([10, 20, 30, 40, 50])

print(f"Array: {arr}")
print(f"First element arr[0]: {arr[0]}")
print(f"Last element arr[-1]: {arr[-1]}")
print(f"Second last arr[-2]: {arr[-2]}")

Array: [10 20 30 40 50]
First element arr[0]: 10
Last element arr[-1]: 50
Second last arr[-2]: 40


In [19]:
# 2D Indexing: arr[row, column]
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print(f"Array:\n{arr_2d}")
print(f"\narr_2d[0, 0] (row 0, col 0): {arr_2d[0, 0]}")
print(f"arr_2d[1, 2] (row 1, col 2): {arr_2d[1, 2]}")
print(f"arr_2d[2, 1] (row 2, col 1): {arr_2d[2, 1]}")

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr_2d[0, 0] (row 0, col 0): 1
arr_2d[1, 2] (row 1, col 2): 6
arr_2d[2, 1] (row 2, col 1): 8


In [20]:
# Modifying elements
arr_2d[0, 0] = 100
print(f"After arr_2d[0,0] = 100:\n{arr_2d}")

After arr_2d[0,0] = 100:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


---
## 9. Array Slicing

Syntax: `arr[start:stop:step]`

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Array: {arr}")

print(f"\narr[1:]: {arr[1:]}      # From index 1 to end")
print(f"arr[:5]: {arr[:5]}      # From start to index 4")
print(f"arr[2:6]: {arr[2:6]}      # Index 2 to 5")
print(f"arr[::2]: {arr[::2]}   # Every 2nd element")
print(f"arr[1::2]: {arr[1::2]}   # Every 2nd, starting at 1")
print(f"arr[::-1]: {arr[::-1]}  # Reversed")

Array: [0 1 2 3 4 5 6 7 8 9]

arr[1:]: [1 2 3 4 5 6 7 8 9]      # From index 1 to end
arr[:5]: [0 1 2 3 4]      # From start to index 4
arr[2:6]: [2 3 4 5]      # Index 2 to 5
arr[::2]: [0 2 4 6 8]   # Every 2nd element
arr[1::2]: [1 3 5 7 9]   # Every 2nd, starting at 1
arr[::-1]: [9 8 7 6 5 4 3 2 1 0]  # Reversed


In [22]:
# 2D Slicing
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print(f"Array:\n{arr_2d}")
print(f"\narr_2d[:2, :3] (first 2 rows, first 3 cols):\n{arr_2d[:2, :3]}")
print(f"\narr_2d[0, :] (first row, all cols): {arr_2d[0, :]}")
print(f"arr_2d[:, 1] (all rows, second col): {arr_2d[:, 1]}")

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr_2d[:2, :3] (first 2 rows, first 3 cols):
[[1 2 3]
 [4 5 6]]

arr_2d[0, :] (first row, all cols): [1 2 3]
arr_2d[:, 1] (all rows, second col): [2 5 8]


---
## 10. Array Copying: Views vs Copies

⚠️ **Important**: Slices create **views**, not copies!

In [23]:
# Views: Changes to slice affect original!
arr = np.array([1, 2, 3, 4, 5])
arr_slice = arr[2:4]  # This is a VIEW

print(f"Original: {arr}")
print(f"Slice: {arr_slice}")

arr_slice[0] = 999  # Modify the slice
print(f"\nAfter modifying slice:")
print(f"Original: {arr}  # Also changed!")
print(f"Slice: {arr_slice}")

Original: [1 2 3 4 5]
Slice: [3 4]

After modifying slice:
Original: [  1   2 999   4   5]  # Also changed!
Slice: [999   4]


In [24]:
# Use .copy() to create independent copy
arr = np.array([1, 2, 3, 4, 5])
arr_copy = arr[2:4].copy()  # This is a COPY

arr_copy[0] = 999
print(f"Original: {arr}  # Not affected")
print(f"Copy: {arr_copy}")

Original: [1 2 3 4 5]  # Not affected
Copy: [999   4]


---
## 11. Reshaping Arrays

Change array dimensions while keeping the same data.

In [25]:
# Reshape 1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Original (1D): {arr}")
print(f"Shape: {arr.shape}")

arr_3x3 = arr.reshape(3, 3)
print(f"\nReshaped (3×3):\n{arr_3x3}")
print(f"Shape: {arr_3x3.shape}")

Original (1D): [1 2 3 4 5 6 7 8 9]
Shape: (9,)

Reshaped (3×3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [26]:
# Row vector and column vector
arr = np.array([1, 2, 3, 4, 5])

row = arr.reshape(1, 5)  # 1 row, 5 columns
col = arr.reshape(5, 1)  # 5 rows, 1 column

print(f"Row vector (1×5):\n{row}")
print(f"\nColumn vector (5×1):\n{col}")

Row vector (1×5):
[[1 2 3 4 5]]

Column vector (5×1):
[[1]
 [2]
 [3]
 [4]
 [5]]


---
## 12. Array Concatenation

In [27]:
# 1D Concatenation
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
z = np.array([99, 99, 99])

combined = np.concatenate([x, y, z])
print(f"Concatenated: {combined}")

Concatenated: [ 1  2  3 10 20 30 99 99 99]


In [28]:
# 2D Concatenation
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original:\n{arr_2d}")

# Vertical concatenation (stack rows)
v_concat = np.concatenate([arr_2d, arr_2d])
print(f"\nVertical concatenation:\n{v_concat}")

Original:
[[1 2 3]
 [4 5 6]]

Vertical concatenation:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [29]:
# vstack (vertical stack) and hstack (horizontal stack)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([7, 8, 9])
col = np.array([[10], [20]])

print(f"vstack (add row):\n{np.vstack([arr_2d, row])}")
print(f"\nhstack (add column):\n{np.hstack([arr_2d, col])}")

vstack (add row):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

hstack (add column):
[[ 1  2  3 10]
 [ 4  5  6 20]]


---
## 13. Array Splitting

In [30]:
# 1D Split
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split at positions 2, 5, 8
n1, n2, n3, n4 = np.split(arr, [2, 5, 8])
print(f"Original: {arr}")
print(f"Split at [2, 5, 8]:")
print(f"  n1: {n1}")
print(f"  n2: {n2}")
print(f"  n3: {n3}")
print(f"  n4: {n4}")

Original: [ 1  2  3  4  5  6  7  8  9 10]
Split at [2, 5, 8]:
  n1: [1 2]
  n2: [3 4 5]
  n3: [6 7 8]
  n4: [ 9 10]


In [31]:
# vsplit and hsplit for 2D arrays
grid = np.arange(16).reshape(4, 4)
print(f"Grid:\n{grid}")

top, bottom = np.vsplit(grid, [2])
print(f"\nvsplit at row 2:")
print(f"Top:\n{top}")
print(f"Bottom:\n{bottom}")

Grid:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

vsplit at row 2:
Top:
[[0 1 2 3]
 [4 5 6 7]]
Bottom:
[[ 8  9 10 11]
 [12 13 14 15]]


In [32]:
left, right = np.hsplit(grid, [2])
print(f"hsplit at column 2:")
print(f"Left:\n{left}")
print(f"Right:\n{right}")

hsplit at column 2:
Left:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Right:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


---
## 14. Fancy Indexing

Access multiple elements using arrays of indices.

In [33]:
arr = np.array([10, 20, 30, 40, 50])

# Get elements at indices 0, 2, 4
indices = [0, 2, 4]
print(f"Array: {arr}")
print(f"arr[{indices}]: {arr[indices]}")

Array: [10 20 30 40 50]
arr[[0, 2, 4]]: [10 30 50]


In [34]:
# Create 2D array using fancy indexing
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([[0, 1], [3, 4]])

result = arr[indices]
print(f"Indices:\n{indices}")
print(f"\nResult:\n{result}")

Indices:
[[0 1]
 [3 4]]

Result:
[[10 20]
 [40 50]]


---
## 📝 Practice Problems

### Problem 1: Min/Max Finder
Create an array of random numbers and find the minimum and maximum values.

In [35]:
# Try it yourself first!

# Solution
def find_min_max(arr):
    """Find min and max values in an array"""
    min_val = arr[0]
    max_val = arr[0]
    
    for value in arr:
        if value > max_val:
            max_val = value
        if value < min_val:
            min_val = value
    
    return min_val, max_val

# Test
arr = np.array([5, 2, 8, 1, 9, 3])
min_v, max_v = find_min_max(arr)
print(f"Array: {arr}")
print(f"Min: {min_v}, Max: {max_v}")

# Note: NumPy has built-in functions: arr.min(), arr.max()

Array: [5 2 8 1 9 3]
Min: 1, Max: 9


### Problem 2: Reciprocal Array
Create a function that returns an array of reciprocals (1/x) for each element.

In [36]:
# Try it yourself first!

# Solution
def find_reciprocal(arr):
    """Return array of reciprocals"""
    result = []
    for value in arr:
        result.append(1 / value)
    return np.array(result)

# Test
arr = np.array([1, 2, 4, 5, 10])
reciprocals = find_reciprocal(arr)
print(f"Original: {arr}")
print(f"Reciprocals: {reciprocals}")

# NumPy way (much faster!): 1 / arr

Original: [ 1  2  4  5 10]
Reciprocals: [1.   0.5  0.25 0.2  0.1 ]


### Problem 3: Filter Greater Than
Create a function that returns elements greater than a given number.

In [37]:
# Try it yourself first!

# Solution
def filter_greater_than(arr, threshold):
    """Return elements greater than threshold"""
    result = []
    for value in arr:
        if value > threshold:
            result.append(value)
    return np.array(result)

# Test
arr = np.array([1, 5, 3, 8, 2, 9, 4])
filtered = filter_greater_than(arr, 4)
print(f"Array: {arr}")
print(f"Greater than 4: {filtered}")

# NumPy way (much faster!): arr[arr > 4]

Array: [1 5 3 8 2 9 4]
Greater than 4: [5 8 9]


---
## 📌 Quick Reference

| Operation | Syntax |
|-----------|--------|
| Create from list | `np.array([1,2,3])` |
| Zeros | `np.zeros(5)` or `np.zeros((3,4))` |
| Ones | `np.ones(5)` or `np.ones((3,4))` |
| Identity | `np.eye(4)` |
| Range | `np.arange(0, 10, 2)` |
| Linspace | `np.linspace(0, 1, 5)` |
| Shape | `arr.shape` |
| Reshape | `arr.reshape(3, 3)` |
| Indexing | `arr[0]`, `arr[0, 1]` |
| Slicing | `arr[1:4]`, `arr[:, 0]` |
| Copy | `arr.copy()` |
| Concatenate | `np.concatenate([a, b])` |
| Split | `np.split(arr, [2, 5])` |