In [2]:
import numpy as np

---
## 1. What are Universal Functions (ufuncs)?

**ufuncs** are vectorized operations that:
- Apply operations element-by-element on arrays
- Push loops into compiled C code (fast!)
- Avoid slow Python loops

**Key concept**: Instead of looping through elements, operate on the entire array at once.

---
## 2. Arithmetic Operations

Standard Python operators work element-wise on arrays.

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(f"Array: {a}")

Array: [1 2 3 4 5]


In [4]:
# Using Python operators (recommended for readability)
print(f"a + 5  = {a + 5}")
print(f"a - 5  = {a - 5}")
print(f"a * 5  = {a * 5}")
print(f"a / 5  = {a / 5}")
print(f"a // 5 = {a // 5}")   # Floor division
print(f"a ** 2 = {a ** 2}")   # Power
print(f"a % 3  = {a % 3}")    # Modulus
print(f"-a     = {-a}")       # Negation

a + 5  = [ 6  7  8  9 10]
a - 5  = [-4 -3 -2 -1  0]
a * 5  = [ 5 10 15 20 25]
a / 5  = [0.2 0.4 0.6 0.8 1. ]
a // 5 = [0 0 0 0 1]
a ** 2 = [ 1  4  9 16 25]
a % 3  = [1 2 0 1 2]
-a     = [-1 -2 -3 -4 -5]


In [5]:
# Equivalent ufuncs (same operations, explicit function calls)
print(f"np.add(a, 5)         = {np.add(a, 5)}")
print(f"np.subtract(a, 5)    = {np.subtract(a, 5)}")
print(f"np.multiply(a, 5)    = {np.multiply(a, 5)}")
print(f"np.divide(a, 5)      = {np.divide(a, 5)}")
print(f"np.floor_divide(a,5) = {np.floor_divide(a, 5)}")
print(f"np.power(a, 2)       = {np.power(a, 2)}")
print(f"np.mod(a, 3)         = {np.mod(a, 3)}")
print(f"np.negative(a)       = {np.negative(a)}")

np.add(a, 5)         = [ 6  7  8  9 10]
np.subtract(a, 5)    = [-4 -3 -2 -1  0]
np.multiply(a, 5)    = [ 5 10 15 20 25]
np.divide(a, 5)      = [0.2 0.4 0.6 0.8 1. ]
np.floor_divide(a,5) = [0 0 0 0 1]
np.power(a, 2)       = [ 1  4  9 16 25]
np.mod(a, 3)         = [1 2 0 1 2]
np.negative(a)       = [-1 -2 -3 -4 -5]


### Operator to ufunc Mapping

| Operator | ufunc | Description |
|----------|-------|-------------|
| `+` | `np.add` | Addition |
| `-` | `np.subtract` | Subtraction |
| `*` | `np.multiply` | Multiplication |
| `/` | `np.divide` | Division |
| `//` | `np.floor_divide` | Floor division |
| `**` | `np.power` | Exponentiation |
| `%` | `np.mod` | Modulus |
| `-x` | `np.negative` | Negation |

---
## 3. Absolute Value Functions

In [6]:
a = np.array([-1, 3, -3, 4, -5])
print(f"Array: {a}")

# Three ways to get absolute value (all equivalent)
print(f"abs(a)         = {abs(a)}")
print(f"np.abs(a)      = {np.abs(a)}")
print(f"np.absolute(a) = {np.absolute(a)}")

Array: [-1  3 -3  4 -5]
abs(a)         = [1 3 3 4 5]
np.abs(a)      = [1 3 3 4 5]
np.absolute(a) = [1 3 3 4 5]


---
## 4. Exponents and Logarithms

In [7]:
x = np.array([1, 2, 3, 4, 5])
print(f"x = {x}")

# Exponents
print(f"\nExponents:")
print(f"e^x (np.exp)    : {np.exp(x)}")
print(f"2^x (np.exp2)   : {np.exp2(x)}")
print(f"3^x (np.power)  : {np.power(3, x)}")

x = [1 2 3 4 5]

Exponents:
e^x (np.exp)    : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
2^x (np.exp2)   : [ 2.  4.  8. 16. 32.]
3^x (np.power)  : [  3   9  27  81 243]


In [8]:
# Logarithms
print(f"x = {x}")
print(f"\nLogarithms:")
print(f"ln(x) (np.log)    : {np.log(x)}")
print(f"log2(x) (np.log2) : {np.log2(x)}")
print(f"log10(x) (np.log10): {np.log10(x)}")

x = [1 2 3 4 5]

Logarithms:
ln(x) (np.log)    : [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log2(x) (np.log2) : [0.         1.         1.5849625  2.         2.32192809]
log10(x) (np.log10): [0.         0.30103    0.47712125 0.60205999 0.69897   ]


### Common Mathematical ufuncs

| Function | Description |
|----------|-------------|
| `np.exp(x)` | $e^x$ |
| `np.exp2(x)` | $2^x$ |
| `np.power(a, x)` | $a^x$ |
| `np.log(x)` | Natural log (ln) |
| `np.log2(x)` | Log base 2 |
| `np.log10(x)` | Log base 10 |
| `np.sqrt(x)` | Square root |
| `np.sin(x)`, `np.cos(x)` | Trigonometric |

---
## 5. Operations on Multi-dimensional Arrays

ufuncs work on arrays of any dimension!

In [9]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(f"2D Array:\n{x}")

2D Array:
[[1 2 3]
 [4 5 6]]


In [10]:
print(f"x + 3:\n{np.add(x, 3)}")
print(f"\nx - 5:\n{np.subtract(x, 5)}")
print(f"\nx ** 2:\n{np.power(x, 2)}")

x + 3:
[[4 5 6]
 [7 8 9]]

x - 5:
[[-4 -3 -2]
 [-1  0  1]]

x ** 2:
[[ 1  4  9]
 [16 25 36]]


---
## 6. Performance: ufuncs vs Python Loops

⚡ **ufuncs are MUCH faster than Python loops!**

In [11]:
# Slow Python loop approach
def find_inverse_loop(arr):
    result = []
    for num in arr:
        result.append(1 / num)
    return np.array(result)

# Test array
big_array = np.random.randint(1, 100, size=10000)

In [12]:
# Time the Python loop
%timeit find_inverse_loop(big_array)

1.65 ms ± 144 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
# Time the ufunc (vectorized)
%timeit (1 / big_array)

15.7 μs ± 902 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


💡 **Takeaway**: The vectorized approach is typically **10-100x faster**!

Always prefer NumPy operations over Python loops for numerical data.

---
## 7. Comparison Operators

Comparison operators return boolean arrays.

In [14]:
x = np.array([1, 2, 3, 4, 5])
print(f"x = {x}")

print(f"\nx < 3  : {x < 3}")
print(f"x > 3  : {x > 3}")
print(f"x == 3 : {x == 3}")
print(f"x != 3 : {x != 3}")
print(f"x <= 3 : {x <= 3}")
print(f"x >= 3 : {x >= 3}")

x = [1 2 3 4 5]

x < 3  : [ True  True False False False]
x > 3  : [False False False  True  True]
x == 3 : [False False  True False False]
x != 3 : [ True  True False  True  True]
x <= 3 : [ True  True  True False False]
x >= 3 : [False False  True  True  True]


In [15]:
# Equivalent ufuncs
print(f"np.less(x, 3)       : {np.less(x, 3)}")
print(f"np.greater(x, 3)    : {np.greater(x, 3)}")
print(f"np.equal(x, 3)      : {np.equal(x, 3)}")
print(f"np.not_equal(x, 3)  : {np.not_equal(x, 3)}")
print(f"np.less_equal(x, 3) : {np.less_equal(x, 3)}")
print(f"np.greater_equal(x,3): {np.greater_equal(x, 3)}")

np.less(x, 3)       : [ True  True False False False]
np.greater(x, 3)    : [False False False  True  True]
np.equal(x, 3)      : [False False  True False False]
np.not_equal(x, 3)  : [ True  True False  True  True]
np.less_equal(x, 3) : [ True  True  True False False]
np.greater_equal(x,3): [False False  True  True  True]


---
## 8. Boolean Aggregation Functions

Work with boolean arrays to count, check conditions.

In [16]:
x = np.random.randint(0, 10, size=(3, 4))
print(f"Random matrix:\n{x}")

Random matrix:
[[3 9 1 6]
 [4 1 3 1]
 [8 4 0 3]]


In [17]:
# Boolean comparison result
print(f"x > 5:\n{x > 5}")

x > 5:
[[False  True False  True]
 [False False False False]
 [ True False False False]]


In [18]:
# Count elements matching condition
print(f"Count where x < 5: {np.sum(x < 5)}")

Count where x < 5: 9


In [19]:
# Count per row (axis=1) or per column (axis=0)
print(f"x:\n{x}")
print(f"\nCount x < 5 per row (axis=1): {np.sum(x < 5, axis=1)}")
print(f"Count x < 5 per column (axis=0): {np.sum(x < 5, axis=0)}")

x:
[[3 9 1 6]
 [4 1 3 1]
 [8 4 0 3]]

Count x < 5 per row (axis=1): [2 4 3]
Count x < 5 per column (axis=0): [2 2 3 2]


In [20]:
# np.any() - Are ANY values True?
# np.all() - Are ALL values True?

print(f"Any x > 5?  {np.any(x > 5)}")
print(f"All x > 5?  {np.all(x > 5)}")
print(f"All x >= 0? {np.all(x >= 0)}")

Any x > 5?  True
All x > 5?  False
All x >= 0? True


In [21]:
# any/all per row or column
print(f"x:\n{x}")
print(f"\nAny x > 5 per row? {np.any(x > 5, axis=1)}")
print(f"Any x > 5 per column? {np.any(x > 5, axis=0)}")

x:
[[3 9 1 6]
 [4 1 3 1]
 [8 4 0 3]]

Any x > 5 per row? [ True False  True]
Any x > 5 per column? [ True  True False  True]


---
## 9. Boolean Operators

Combine conditions with `&` (and), `|` (or), `~` (not).

⚠️ **Note**: Use `&`, `|`, `~` instead of Python's `and`, `or`, `not`

In [22]:
x = np.random.randint(0, 10, size=(3, 4))
print(f"x:\n{x}")

x:
[[1 6 8 4]
 [4 8 4 9]
 [1 7 1 7]]


In [23]:
# AND condition: values between 3 and 7
count_between = np.sum((x > 3) & (x < 7))
print(f"Count where 3 < x < 7: {count_between}")

Count where 3 < x < 7: 4


In [24]:
# OR condition: values equal to 5 or 8
count_5_or_8 = np.sum((x == 5) | (x == 8))
print(f"Count where x == 5 or x == 8: {count_5_or_8}")

Count where x == 5 or x == 8: 2


In [25]:
# NOT condition: count values NOT 5 or 8
count_not_5_or_8 = np.sum(~((x == 5) | (x == 8)))
print(f"Count where x is NOT 5 or 8: {count_not_5_or_8}")

Count where x is NOT 5 or 8: 10


### Boolean Operator Reference

| Operator | ufunc | Description |
|----------|-------|-------------|
| `&` | `np.bitwise_and` | Element-wise AND |
| `\|` | `np.bitwise_or` | Element-wise OR |
| `~` | `np.bitwise_not` | Element-wise NOT |
| `^` | `np.bitwise_xor` | Element-wise XOR |

---
## 10. Boolean Masking (Filtering)

Use boolean arrays to **extract** elements matching a condition.

In [26]:
x = np.random.randint(0, 10, size=(3, 4))
print(f"x:\n{x}")

x:
[[4 2 1 8]
 [8 3 3 4]
 [4 6 1 3]]


In [27]:
# Boolean condition
print(f"x < 5:\n{x < 5}")

x < 5:
[[ True  True  True False]
 [False  True  True  True]
 [ True False  True  True]]


In [28]:
# Extract elements using boolean indexing (masking)
values_less_than_5 = x[x < 5]
print(f"Values where x < 5: {values_less_than_5}")

Values where x < 5: [4 2 1 3 3 4 4 1 3]


In [29]:
# Create and use a mask variable
mask = x < 8
print(f"Mask (x < 8):\n{mask}")
print(f"\nFiltered values: {x[mask]}")

Mask (x < 8):
[[ True  True  True False]
 [False  True  True  True]
 [ True  True  True  True]]

Filtered values: [4 2 1 3 3 4 4 6 1 3]


In [30]:
# Complex mask with multiple conditions
complex_mask = (x > 3) & (x < 8)
print(f"Values where 3 < x < 8: {x[complex_mask]}")

Values where 3 < x < 8: [4 4 4 6]


---
## 📝 Practice Problems

### Problem 1: Temperature Conversion
Convert an array of Celsius temperatures to Fahrenheit using vectorized operations.
Formula: F = C × 9/5 + 32

In [31]:
# Try it yourself first!

# Solution
celsius = np.array([0, 10, 20, 25, 30, 37, 100])
fahrenheit = celsius * 9/5 + 32

print(f"Celsius:    {celsius}")
print(f"Fahrenheit: {fahrenheit}")

Celsius:    [  0  10  20  25  30  37 100]
Fahrenheit: [ 32.   50.   68.   77.   86.   98.6 212. ]


### Problem 2: Filter Outliers
Given an array, extract values that are within 2 standard deviations of the mean.

In [32]:
# Try it yourself first!

# Solution
data = np.array([2, 4, 5, 6, 7, 100, 8, 3, 5, -50, 6, 7])

mean = np.mean(data)
std = np.std(data)

# Create mask for values within 2 std deviations
mask = (data > mean - 2*std) & (data < mean + 2*std)
filtered = data[mask]

print(f"Original: {data}")
print(f"Mean: {mean:.2f}, Std: {std:.2f}")
print(f"Range: ({mean - 2*std:.2f}, {mean + 2*std:.2f})")
print(f"Filtered: {filtered}")

Original: [  2   4   5   6   7 100   8   3   5 -50   6   7]
Mean: 8.58, Std: 31.53
Range: (-54.47, 71.64)
Filtered: [  2   4   5   6   7   8   3   5 -50   6   7]


### Problem 3: Count Pass/Fail
Given exam scores, count how many passed (≥60) and failed (<60).

In [33]:
# Try it yourself first!

# Solution
scores = np.array([85, 45, 72, 58, 90, 62, 55, 78, 42, 95])

passed = np.sum(scores >= 60)
failed = np.sum(scores < 60)

print(f"Scores: {scores}")
print(f"Passed (≥60): {passed}")
print(f"Failed (<60): {failed}")
print(f"Pass rate: {passed / len(scores) * 100:.1f}%")

Scores: [85 45 72 58 90 62 55 78 42 95]
Passed (≥60): 6
Failed (<60): 4
Pass rate: 60.0%


---
## 📌 Quick Reference

### Arithmetic ufuncs
| Operation | Operator | ufunc |
|-----------|----------|-------|
| Add | `+` | `np.add` |
| Subtract | `-` | `np.subtract` |
| Multiply | `*` | `np.multiply` |
| Divide | `/` | `np.divide` |
| Power | `**` | `np.power` |

### Comparison ufuncs
| Operation | Operator | ufunc |
|-----------|----------|-------|
| Less than | `<` | `np.less` |
| Greater than | `>` | `np.greater` |
| Equal | `==` | `np.equal` |
| Not equal | `!=` | `np.not_equal` |

### Boolean operations
| Function | Description |
|----------|-------------|
| `np.any(condition)` | True if any element matches |
| `np.all(condition)` | True if all elements match |
| `np.sum(condition)` | Count of True values |
| `arr[condition]` | Extract matching elements (masking) |